[project]
name = "mcp-trial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "yfinance",
    "asyncio",
    "langchain-mcp-adapters",
    "langgraph",
    "fastmcp",
    "langchain_google_genai"
]
